### ISSUE TITLE
Implementation of Scrypt

### ISSUE THREAD

**Issue by artforlife** [eudoxia0/cl-pass#7]
Are you planning to implement the Scrypt algorithm or are you aware of any implementations for Common Lisp?

**Comment by eudoxia0** [comment]
No and no. I'm not cryptographically literate enough to implement scrypt and I don't know of any implementations for CL.

**Comment by dertuxmalwieder** [comment]
@artforlife FWIW, Ironclad (which `cl-pass` uses anyway) [does support Scrypt](https://github.com/sharplispers/ironclad/blob/master/src/kdf/scrypt.lisp) these days.

@eudoxia0 That might or might not solve https://github.com/eudoxia0/hermetic/issues/7 😏
